[core]
    engine = pg
    plan_file = sqitch.plan
    top_dir = .

[engine "pg"]
    target = local
    registry = sqitch
    client = psql

[target "local"]
    uri = db:pg://localhost:5434/churn_dev

# [target "dev"]
#     # Usa variáveis libpq: PGHOST, PGPORT, PGUSER, PGPASSWORD, PGDATABASE
#     uri = db:pg:
